const serviceActions= {
    get_event_data:'GET_EVENT_DATA',
    get_event_data_err:'GET_EVENT_DATA_ERR',
    get_latest_device_loc:'GET_LATEST_DEVICE_LOC',
    get_latest_device_loc_err:'GET_LATEST_DEVICE_LOC_ERR',
    get_srlogistics:'GET_SRLOGISTICS',
    get_srlogistics_err:'GET_SRLOGISTICS_ERR',
    get_srlogistics_lat_loc:'GET_SRLOGISTICS_LAT_LOC',
    get_srlogistics_lat_loc_err:'GET_SRLOGISTICS_LAT_LOC_ERR',
    get_srlgoistics_reload_data:'GET_SRLOGISTICS_RELOAD_DATA',
    delete_all:'DELETE_ALL',
    delete_all_err:'DELETE_ALL_ERR',
    cre_event_data:'CRE_EVENT_DATA',
    cre_event_data_err:'CRE_EVENT_DATA_ERR',
    get_grp_map_events:'GET_GRP_MAP_EVENTS',
    get_grp_map_events_err:'GET_GRP_MAP_EVENTS_ERR',
    track_events_by_veh:'TRACK_EVENTS_BY_VEH',
    track_events_by_veh_err:'TRACK_EVENTS_BY_VEH_ERR',
    get_account_data:'GET_ACCOUNT_DATA',
    get_account_data_err:'GET_ACCOUNT_DATA_ERR',
    get_employee_data:'GET_EMPLOYEE_DATA',
    get_employee_data_err:'GET_EMPLOYEE_DATA_ERR'
};
module.exports=serviceActions;